// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdgAv3iXDiq6iTbRkcN_0nqBaoK87y3e4',
    appId: '1:223179862210:web:3661b0c0a0c770566fcb5b',
    messagingSenderId: '223179862210',
    projectId: 'fir-login-check-75276',
    authDomain: 'fir-login-check-75276.firebaseapp.com',
    storageBucket: 'fir-login-check-75276.appspot.com',
    measurementId: 'G-D7YWJNPE6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDC1z-W-txUxJavMjGefnueGzIhaLPoAc',
    appId: '1:223179862210:android:c3b174289125cb846fcb5b',
    messagingSenderId: '223179862210',
    projectId: 'fir-login-check-75276',
    storageBucket: 'fir-login-check-75276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw29BIqkPcMGrpIkk9HwKffKmCF7Wzltc',
    appId: '1:223179862210:ios:76758d12986fd18e6fcb5b',
    messagingSenderId: '223179862210',
    projectId: 'fir-login-check-75276',
    storageBucket: 'fir-login-check-75276.appspot.com',
    iosClientId: '223179862210-f90jco4kfvq2hk74fp8op9nv63qp0gua.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw29BIqkPcMGrpIkk9HwKffKmCF7Wzltc',
    appId: '1:223179862210:ios:83ff3a6de9beef8a6fcb5b',
    messagingSenderId: '223179862210',
    projectId: 'fir-login-check-75276',
    storageBucket: 'fir-login-check-75276.appspot.com',
    iosClientId: '223179862210-mof0uu5ifkm923256rmsdqc223hektes.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseLoginCheck.RunnerTests',
  );
}
